heart_failure:
    nyha_class: ['18853','13189','19066','51214'] #medcodes pertaining to class I, II, III & IV
    hf_subtype_med:  #from Nathalie's paper
        '884': 'HF-UNS'
        '2062': 'HF-UNS'
        '2906': 'HF-UNS'
        '398': 'HF-UNS'
        '8966': 'HF-REF'
        '3204': 'HF-UNS'
        '11284': 'HF-REF'
        '1223': 'HF-UNS'
        '5942': 'HF-REF'
        '7251': 'HF-REF'
        '9913': 'HF-UNS'
        '12550': 'HF-UNS'
        '8010': 'HF-REF'
        '5695': 'HF-UNS'
        '4024': 'HF-UNS'
        '11351': 'HF-REF'
        '7535': 'HF-REF'
        '13189': 'HF-UNS'
        '5255': 'HF-UNS'
        '10079': 'HF-UNS'
        '3499': 'HF-REF'
        '16383': 'HF-UNS'
        '9524': 'HF-UNS'
        '7320': 'HF-REF'
        '17278': 'HF-UNS'
        '19066': 'HF-UNS'
        '27964': 'HF-UNS'
        '22993': 'HF-UNS'
        '107397': 'HF-REF'
        '18853': 'HF-UNS'
        '101138': 'HF-UNS'
        '32671': 'HF-UNS'
        '4915': 'HF-REF'
        '10154': 'HF-UNS'
        '9402': 'HF-REF'
        '27884': 'HF-UNS'
        '32898': 'HF-UNS'
        '21852': 'HF-UNS'
        '106897': 'HF-UNS'
        '104275': 'HF-UNS'
        '5141': 'HF-UNS'
        '11424': 'HF-UNS'
        '97780': 'HF-REF'
        '101137': 'HF-UNS'
        '106008': 'HF-UNS'
        '94870': 'HF-UNS'
        '27683': 'HF-UNS'
        '70648': 'HF-REF'
        '22262': 'HF-UNS'
        '51214': 'HF-UNS'
        '106198': 'HF-UNS'
        '103732': 'HF-UNS'
        '62718': 'HF-UNS'
        '52127': 'HF-UNS'
        '21837': 'HF-UNS'
        '105542': 'HF-UNS'
    hf_subtype_ICD10:
        'I50.0': 'HF-UNS'
        'I50.1': 'HF-UNS'
        'I50.9': 'HF-UNS'
        'I42.0': 'HF-REF'
        'I42.9': 'HF-UNS'
        'I11.0': 'HF-UNS'
        'I25.5': 'HF-REF'
        'I13.2': 'HF-UNS'
        'I13.0': 'HF-UNS'

    

    